#!/bin/sh

# test-10032026-Maurice
# test-10042026-Maurice: exact lifecycle migration inventory regression guard.
# Ticket 08 RED contract: approval/reopen lifecycle, immutable approved data,
# lifecycle events/audit visibility, and approved-only reporting.
# Mapped to TC0005/0006/0009/0010/0022/0027-0031.
set -eu
umask 077
MAX_FAILURES=1
REPO_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
COMPOSE_FILE=$REPO_ROOT/compose.yaml
PROJECT_NAME=${OJT_TEST_COMPOSE_PROJECT:-ojt-ticket08-$$}
APP_PORT=${OJT_TEST_APP_PORT:-$((18300 + ($$ % 600)))}
TMP_ROOT=${TMPDIR:-/tmp}/ojt-ticket08-$$
COMPOSE_STARTED=0
mkdir -p "$TMP_ROOT"
trap 'if [ "$COMPOSE_STARTED" = 1 ]; then docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" down --volumes --remove-orphans >/dev/null 2>&1 || :; fi; rm -rf -- "$TMP_ROOT"' EXIT HUP INT TERM
logger -t ojt-ticket08 "event=startup status=begin test=ticket08_lifecycle_test max_failures=$MAX_FAILURES" || :

# Static gates deliberately precede Docker and provide the initial RED.
logger -t ojt-ticket08 'event=major-operation status=check cases=TC0005,TC0006,TC0009,TC0010,TC0022,TC0027,TC0028,TC0029,TC0030,TC0031 assertion=lifecycle-artifacts' || :
LIFECYCLE_MIGRATION="$REPO_ROOT/database/migrations/2026_10_04_000001_create_internship_lifecycle_events_table.php"
[ -f "$LIFECYCLE_MIGRATION" ] || { printf '%s\n' 'FAIL [TC0005]: exact lifecycle event migration is missing (Docker not started)' >&2; exit 1; }
grep -Eq '^class[[:space:]]+CreateInternshipLifecycleEventsTable[[:space:]]+extends[[:space:]]+Migration' "$LIFECYCLE_MIGRATION" || { printf '%s\n' 'FAIL [TC0005]: lifecycle migration class/schema target is not exact (Docker not started)' >&2; exit 1; }
grep -Eq "Schema::create\('internship_lifecycle_events'|bigIncrements\('id'\)|unsignedInteger\('internship_id'\)|unsignedInteger\('actor_id'\)|string\('event_type', 16\)|boolean\('from_is_approved'\)|boolean\('to_is_approved'\)|string\('reason', 500\)->nullable" "$LIFECYCLE_MIGRATION" || { printf '%s\n' 'FAIL [TC0005]: lifecycle event schema columns are incomplete (Docker not started)' >&2; exit 1; }
grep -Fq "foreign('internship_id')->references('id')->on('internships')->onDelete('restrict')" "$LIFECYCLE_MIGRATION" || { printf '%s\n' 'FAIL [TC0005]: internship lifecycle foreign key is missing (Docker not started)' >&2; exit 1; }
grep -Fq "foreign('actor_id')->references('id')->on('users')->onDelete('restrict')" "$LIFECYCLE_MIGRATION" || { printf '%s\n' 'FAIL [TC0005]: actor lifecycle foreign key is missing (Docker not started)' >&2; exit 1; }
grep -Fq 'CREATE TRIGGER internship_lifecycle_events_before_insert' "$LIFECYCLE_MIGRATION" || { printf '%s\n' 'FAIL [TC0005]: lifecycle insert trigger is missing (Docker not started)' >&2; exit 1; }
grep -Fq 'CREATE TRIGGER internship_lifecycle_events_before_update' "$LIFECYCLE_MIGRATION" || { printf '%s\n' 'FAIL [TC0005]: lifecycle update immutability trigger is missing (Docker not started)' >&2; exit 1; }
grep -Fq 'CREATE TRIGGER internship_lifecycle_events_before_delete' "$LIFECYCLE_MIGRATION" || { printf '%s\n' 'FAIL [TC0005]: lifecycle delete immutability trigger is missing (Docker not started)' >&2; exit 1; }
grep -Fq 'DROP TRIGGER IF EXISTS internship_lifecycle_events_before_insert' "$LIFECYCLE_MIGRATION" || { printf '%s\n' 'FAIL [TC0005]: lifecycle down cleanup is missing (Docker not started)' >&2; exit 1; }
[ -f "$REPO_ROOT/app/InternshipLifecycleEvent.php" ] || { printf '%s\n' 'FAIL [TC0005]: lifecycle event model is missing (Docker not started)' >&2; exit 1; }
grep -Eiq 'approve|reopen' "$REPO_ROOT/routes/api.php" || { printf '%s\n' 'FAIL [TC0006]: approve/reopen routes are missing (Docker not started)' >&2; exit 1; }
grep -Eiq 'events|lifecycle' "$REPO_ROOT/routes/api.php" || { printf '%s\n' 'FAIL [TC0005]: lifecycle event read route is missing (Docker not started)' >&2; exit 1; }
grep -Eiq 'public function approve|public function reopen' "$REPO_ROOT/app/Http/Controllers/InternshipController.php" || { printf '%s\n' 'FAIL [TC0006]: approve/reopen methods are missing (Docker not started)' >&2; exit 1; }
grep -Eiq 'DB::transaction|lockForUpdate' "$REPO_ROOT/app/Services/InternshipLifecycleService.php" || { printf '%s\n' 'FAIL [TC0009]: lifecycle transaction/row locks are missing (Docker not started)' >&2; exit 1; }
grep -Eiq 'audit|lifecycle.?event|event.*create|reason' "$REPO_ROOT/app/Http/Controllers/InternshipController.php" "$REPO_ROOT/app/InternshipLifecycleEvent.php" || { printf '%s\n' 'FAIL [TC0005]: lifecycle audit write is missing (Docker not started)' >&2; exit 1; }
grep -Eiq 'is_approved.*1|where.*is_approved.*1|approved' "$REPO_ROOT/app/Services/InternshipReportingService.php" || { printf '%s\n' 'FAIL [TC0022]: reporting lacks authoritative approved filter (Docker not started)' >&2; exit 1; }
grep -Eiq "internships/report/pdf|report.*pdf" "$REPO_ROOT/routes/api.php" "$REPO_ROOT/app/Http/Controllers/InternshipReportingController.php" || { printf '%s\n' 'FAIL [TC0022]: reporting PDF contract is missing (Docker not started)' >&2; exit 1; }
grep -Eiq 'SessionTracer::enter|SessionTracer::leave|SessionTracer::exception|catch[[:space:]]*\([^)]*Throwable' "$REPO_ROOT/app/Http/Controllers/InternshipController.php" "$REPO_ROOT/app/Services/InternshipReportingService.php" || { printf '%s\n' 'FAIL [TC0031]: lifecycle/reporting trace envelope is missing (Docker not started)' >&2; exit 1; }
[ -f "$COMPOSE_FILE" ] || { printf '%s\n' 'FAIL [TC0031]: compose.yaml is required' >&2; exit 1; }
command -v docker >/dev/null 2>&1 || { printf '%s\n' 'FAIL [TC0031]: docker is required' >&2; exit 1; }
command -v timeout >/dev/null 2>&1 || { printf '%s\n' 'FAIL [TC0031]: timeout is required' >&2; exit 1; }
command -v curl >/dev/null 2>&1 || { printf '%s\n' 'FAIL [TC0031]: curl is required' >&2; exit 1; }
if command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 "$APP_PORT" >/dev/null 2>&1; then printf '%s\n' 'FAIL [TC0031]: selected app port is already in use' >&2; exit 1; fi

# Container-only Passport probe. Tokens and fixture identities never reach output.
cat >"$TMP_ROOT/lifecycle_probe.php" <<'PHP'
<?php
$base=rtrim(getenv('OJT_PROBE_BASE_URL'),'/');$corr='ticket08-correlation';
$a=App\User::firstOrCreate(['sr_code'=>'T08-A'],['name'=>'Ticket08 A','email'=>'t08-a@example.invalid','password'=>bcrypt('t08-a'),'role'=>'student']);
$b=App\User::firstOrCreate(['sr_code'=>'T08-B'],['name'=>'Ticket08 B','email'=>'t08-b@example.invalid','password'=>bcrypt('t08-b'),'role'=>'student']);
$c=App\User::firstOrCreate(['sr_code'=>'T08-C'],['name'=>'Ticket08 C','email'=>'t08-c@example.invalid','password'=>bcrypt('t08-c'),'role'=>'coordinator']);
$s=App\User::firstOrCreate(['sr_code'=>'T08-S'],['name'=>'Ticket08 S','email'=>'t08-s@example.invalid','password'=>bcrypt('t08-s'),'role'=>'superuser']);
$x=App\User::firstOrCreate(['sr_code'=>'T08-X'],['name'=>'Ticket08 X','email'=>'t08-x@example.invalid','password'=>bcrypt('t08-x'),'role'=>'unknown']);
$pc=Illuminate\Support\Facades\DB::table('oauth_personal_access_clients')->first();if(!$pc){$id=Illuminate\Support\Facades\DB::table('oauth_clients')->insertGetId(['user_id'=>null,'name'=>'T08','secret'=>hash('sha256','t08'),'redirect'=>'http://localhost','personal_access_client'=>1,'password_client'=>0,'revoked'=>0]);Illuminate\Support\Facades\DB::table('oauth_personal_access_clients')->insert(['client_id'=>$id]);}
$tok=[];foreach(['a'=>$a,'b'=>$b,'c'=>$c,'s'=>$s,'x'=>$x] as $k=>$u)$tok[$k]=(string)app(Laravel\Passport\PersonalAccessTokenFactory::class)->make($u->id,'ticket08')->accessToken;
$call=function($who,$method,$path,$body,$want)use($base,$corr,$tok){$h=['Accept: application/json','X-Correlation-ID: '.$corr];if($body!=='')$h[]='Content-Type: application/json';if($who!=='guest')$h[]='Authorization: Bearer '.$tok[$who];$q=curl_init($base.$path);curl_setopt_array($q,[CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_POSTFIELDS=>$body,CURLOPT_HTTPHEADER=>$h,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_CONNECTTIMEOUT=>2,CURLOPT_TIMEOUT=>8]);$r=curl_exec($q);$code=curl_getinfo($q,CURLINFO_HTTP_CODE);curl_close($q);if($code!==$want)throw new RuntimeException('status');$safeRaw=str_replace($corr,'',preg_replace('/^X-Correlation-ID:.*$/im','',$r));if($code>=400&&preg_match('/token|password|email|phone|address|T08-/i',$safeRaw))throw new RuntimeException('unsafe-error');$p=preg_split("/\r?\n\r?\n/",$r,2);return [$r,json_decode($p[1]??'',true)];};
$company=App\Company::where('is_deleted','0')->firstOrFail();$made=$call('a','POST','/api/internships',json_encode(['company_id'=>$company->id,'start_date'=>'2099-08-01','end_date'=>'2099-08-31','representative'=>'T08 Rep','student_position'=>'T08 Position']),201);$iid=(int)($made[1]['data']['id']??$made[1]['id']??0);if(!$iid)throw new RuntimeException('placement-id');
$call('a','POST','/api/descriptions',json_encode(['internship_id'=>$iid,'description'=>'']),422);$call('a','POST','/api/descriptions',json_encode(['internship_id'=>$iid,'description'=>'   ']),422);$d=App\Description::create(['internship_id'=>$iid,'description'=>'T08 temporary evidence','is_deleted'=>0]);$call('a','POST','/api/descriptions/'.$d->id,json_encode(['description'=>'']),422);$call('a','POST','/api/descriptions/'.$d->id,json_encode(['description'=>'   ']),422);$call('a','DELETE','/api/descriptions/'.$d->id,'',204);if(App\Description::where('internship_id',$iid)->where('is_deleted','0')->exists())throw new RuntimeException('blank-description-persisted');
$cats=App\RequirementCategory::where('is_deleted','0')->get();foreach($cats as $cat)App\Requirement::updateOrCreate(['internship_id'=>$iid,'requirement_category_id'=>$cat->id],['is_approved'=>1,'is_deleted'=>0,'updated_by'=>$c->id]);App\Report::create(['internship_id'=>$iid,'description'=>'T08 valid','date'=>'2099-08-03','hours'=>'8','is_valid'=>1,'is_deleted'=>0,'updated_by'=>$a->id]);$i=App\Internship::findOrFail($iid);$i->status='arbitrary';$i->is_approved=0;$i->save();
$rows=$call('c','POST','/api/internships/report',json_encode(['page'=>1,'per_page'=>100]),200)[1]['data']??[];foreach($rows as $row)if((int)($row['id']??0)===$iid)throw new RuntimeException('unapproved-reportable');
$call('a','POST','/api/internships/'.$iid.'/approve','{}',403);$call('c','POST','/api/internships/'.$iid.'/approve','{}',200);$i->refresh();if((int)$i->is_approved!==1||(string)$i->status!=='approved'||(int)$i->updated_by!==(int)$c->id)throw new RuntimeException('approval-persistence');$events=App\InternshipLifecycleEvent::where('internship_id',$iid)->orderBy('id')->get();if($events->count()!==1||(string)$events[0]->event_type!=='approved')throw new RuntimeException('approval-event');$call('c','POST','/api/internships/'.$iid.'/approve','{}',200);if(App\InternshipLifecycleEvent::where('internship_id',$iid)->where('event_type','approved')->count()!==1)throw new RuntimeException('duplicate-event');
$event=App\InternshipLifecycleEvent::where('internship_id',$iid)->firstOrFail();$eventData=['internship_id'=>$iid,'actor_id'=>$c->id,'event_type'=>'approved','from_is_approved'=>0,'to_is_approved'=>1,'reason'=>null,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')];$reject=function($operation,$label){$blocked=false;try{$operation();}catch(\Throwable $e){$blocked=true;}if(!$blocked)throw new RuntimeException($label);};$reject(function()use($event){Illuminate\Support\Facades\DB::table('internship_lifecycle_events')->where('id',$event->id)->update(['reason'=>'tampered']);},'event-update-not-blocked');$reject(function()use($event){Illuminate\Support\Facades\DB::table('internship_lifecycle_events')->where('id',$event->id)->delete();},'event-delete-not-blocked');foreach([['internship_id'=>999999999],['event_type'=>'invalid'],['from_is_approved'=>1,'to_is_approved'=>1],['reason'=>str_repeat('x',501)]] as $bad){$invalid=array_merge($eventData,$bad);$reject(function()use($invalid){Illuminate\Support\Facades\DB::table('internship_lifecycle_events')->insert($invalid);},'event-constraint-not-blocked');}
$d=App\Description::create(['internship_id'=>$iid,'description'=>'T08 evidence','is_deleted'=>0]);$r=App\Report::create(['internship_id'=>$iid,'description'=>'T08 report','date'=>'2099-08-04','hours'=>'8','is_valid'=>1,'is_deleted'=>0,'updated_by'=>$a->id]);$q=App\Requirement::where('internship_id',$iid)->firstOrFail();foreach([['a','POST','/api/descriptions/'.$d->id,json_encode(['description'=>'x']),403],['c','DELETE','/api/descriptions/'.$d->id,'',403],['a','POST','/api/reports/'.$r->id,json_encode(['description'=>'x']),403],['s','DELETE','/api/reports/'.$r->id,'',403],['c','POST','/api/requirements/'.$q->id,json_encode(['is_approved'=>0]),403],['c','POST','/api/internships/'.$iid,json_encode(['status'=>'x']),403]] as $z)$call($z[0],$z[1],$z[2],$z[3],$z[4]);
foreach([['a',403],['x',403],['b',403]] as $z)$call($z[0],'POST','/api/internships/'.$iid.'/reopen',json_encode(['reason'=>'valid reopen reason']),$z[1]);$call('c','POST','/api/internships/999999/reopen',json_encode(['reason'=>'valid reopen reason']),404);foreach(['','short',str_repeat('x',501)] as $reason)$call('c','POST','/api/internships/'.$iid.'/reopen',json_encode(['reason'=>$reason]),422);$call('c','POST','/api/internships/'.$iid.'/reopen',json_encode(['reason'=>'valid reopen reason']),200);$i->refresh();if((int)$i->is_approved!==0||(string)$i->status!=='pending')throw new RuntimeException('reopen-persistence');if(App\InternshipLifecycleEvent::where('internship_id',$iid)->where('event_type','reopened')->count()!==1)throw new RuntimeException('reopen-event');$call('c','POST','/api/internships/'.$iid.'/reopen',json_encode(['reason'=>'valid reopen reason']),409);
$i->status='approved';$i->is_approved=0;$i->save();$rows=$call('c','POST','/api/internships/report',json_encode(['page'=>1,'per_page'=>100]),200)[1]['data']??[];foreach($rows as $row)if((int)($row['id']??0)===$iid)throw new RuntimeException('status-not-authoritative');$q->is_approved=0;$q->save();$call('c','POST','/api/internships/'.$iid.'/approve','{}',422);$q->is_approved=1;$q->save();$call('s','POST','/api/internships/'.$iid.'/approve','{}',200);$events=App\InternshipLifecycleEvent::where('internship_id',$iid)->orderBy('created_at')->orderBy('id')->get();if($events->count()!==3)throw new RuntimeException('event-order-or-count');$call('s','POST','/api/internships/'.$iid.'/reopen',json_encode(['reason'=>'superuser correction reason']),200);$i->refresh();if((int)$i->is_approved!==0||(string)$i->status!=='pending')throw new RuntimeException('superuser-reopen');$call('a','POST','/api/internships/'.$iid,'{}',200);$q->is_approved=1;$q->save();$call('c','POST','/api/internships/'.$iid.'/approve','{}',200);$events=App\InternshipLifecycleEvent::where('internship_id',$iid)->orderBy('created_at')->orderBy('id')->get();if($events->count()!==5)throw new RuntimeException('event-order-or-count');$visible=$call('a','GET','/api/internships/'.$iid.'/events','',200)[1];if(!is_array($visible))throw new RuntimeException('event-read');$call('b','GET','/api/internships/'.$iid.'/events','',403);$call('c','GET','/api/internships/'.$iid.'/events','',200);$pdf=$call('c','POST','/api/internships/report/pdf',json_encode(['page'=>1,'per_page'=>100]),200);if(stripos($pdf[0],'application/pdf')===false)throw new RuntimeException('pdf-not-approved-report');
 $i->is_approved=0;$i->status='pending';$i->save();$alreadyUnapproved=$call('c','POST','/api/internships/'.$iid.'/reopen',json_encode(['reason'=>'valid reopen reason']),409)[1];if(!is_array($alreadyUnapproved)||array_keys($alreadyUnapproved)!==['error','correlation_id']||!is_array($alreadyUnapproved['error'])||array_keys($alreadyUnapproved['error'])!==['code','message']||$alreadyUnapproved['correlation_id']!==$corr||!is_string($alreadyUnapproved['error']['code'])||!is_string($alreadyUnapproved['error']['message']))throw new RuntimeException('reopen-safe-error');echo 'runtime=ready lifecycle=verified reporting=approved-only'.PHP_EOL;
PHP

export COMPOSE_PROJECT_NAME="$PROJECT_NAME" APP_PORT OJT_PROBE_BASE_URL=${OJT_PROBE_BASE_URL:-http://nginx:8080} PROVIDER_MODE=fake OJT_TEST_NO_PROVIDER_CALLS=1
timeout "${OJT_TEST_BUILD_TIMEOUT_SECONDS:-180}" docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" up -d --build >"$TMP_ROOT/compose.log" 2>&1
COMPOSE_STARTED=1
chmod 0644 "$TMP_ROOT/lifecycle_probe.php"
timeout 20 docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" cp "$TMP_ROOT/lifecycle_probe.php" php-fpm:/tmp/lifecycle_probe.php >"$TMP_ROOT/copy.log" 2>&1
timeout 30 docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" exec -T -e OJT_PROBE_BASE_URL="$OJT_PROBE_BASE_URL" php-fpm sh -c 'export APP_KEY=$(cat /run/ojt-secrets/app.key); export DB_PASSWORD=$(cat /run/ojt-secrets/db.app.password); php -r '\''require "/var/www/html/vendor/autoload.php"; $app=require "/var/www/html/bootstrap/app.php"; $app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap(); require "/tmp/lifecycle_probe.php";'\''' >"$TMP_ROOT/probe.log" 2>&1 || { printf '%s\n' 'FAIL [TC0031]: lifecycle runtime probe failed' >&2; sed -n '1,30p' "$TMP_ROOT/probe.log" >&2; exit 1; }
if grep -Eiq 'token|password|email|phone|address|T08-|secret|api[_-]?key' "$TMP_ROOT/probe.log"; then printf '%s\n' 'FAIL [TC0031]: runtime output contains secret or fixture data' >&2; exit 1; fi
logger -t ojt-ticket08 'event=pass status=complete test=ticket08_lifecycle_test' || :
printf '%s\n' 'PASS: Ticket 08 lifecycle contract'
