#!/bin/sh

# test-10032026-Maurice
# Ticket 06 RED contract: placement creation/atomic requirements and evidence
# ownership, validation, pagination, soft deletion, and approval immutability.
# Mapped to TC-OJT-0003/0004/0007/0010/0011/0025/0026/0027.
set -eu
umask 077
REPO_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
COMPOSE_FILE=$REPO_ROOT/compose.yaml
PROJECT_NAME=${OJT_TEST_COMPOSE_PROJECT:-ojt-ticket06-$$}
APP_PORT=${OJT_TEST_APP_PORT:-$((18200 + ($$ % 700)))}
TMP_ROOT=${TMPDIR:-/tmp}/ojt-ticket06-$$
COMPOSE_STARTED=0
TRIGGER_INSTALLED=0
AGENT_SESSION_ID=${AGENT_SESSION_ID:-ticket06-$$}
mkdir -p "$TMP_ROOT"
trap 'if [ "$TRIGGER_INSTALLED" = 1 ]; then docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" exec -T mariadb sh -c "mariadb -uroot -p\"\$(cat /run/ojt-secrets/db.root.password)\" \"\${DB_DATABASE:-ojt_tracker}\" -e \"DROP TRIGGER IF EXISTS ticket06_requirement_failure\"" >/dev/null 2>&1 || :; fi; if [ "$COMPOSE_STARTED" = 1 ]; then docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" down --volumes --remove-orphans >/dev/null 2>&1 || :; fi; rm -rf -- "$TMP_ROOT"' EXIT HUP INT TERM
logger -t ojt-ticket06 "event=startup status=begin test=ticket06_placement_evidence_test max_failures=1" || :

# Static gates are deliberately before Docker. They prove the API surface and
# changed-method trace envelope, and produce the expected immediate RED on the
# current branch (the show routes are not yet registered).
logger -t ojt-ticket06 'event=major-operation status=check cases=TC-OJT-0003,TC-OJT-0004,TC-OJT-0007 assertion=placement-evidence-routes' || :
grep -Eq "^[[:space:]]*Route::get\('/descriptions/\{id\}'|^[[:space:]]*Route::get\([^;]*descriptions/\{id\}[^;]*DescriptionController@show" "$REPO_ROOT/routes/api.php" || { logger -t ojt-ticket06 'event=failure status=red case=TC-OJT-0025 assertion=description-show-route' || :; printf '%s\n' 'FAIL [TC-OJT-0025]: description show route is missing (Docker not started)' >&2; exit 1; }
grep -Eq "^[[:space:]]*Route::get\('/reports/\{id\}'|^[[:space:]]*Route::get\([^;]*reports/\{id\}[^;]*ReportController@show" "$REPO_ROOT/routes/api.php" || { logger -t ojt-ticket06 'event=failure status=red case=TC-OJT-0026 assertion=report-show-route' || :; printf '%s\n' 'FAIL [TC-OJT-0026]: report show route is missing (Docker not started)' >&2; exit 1; }
grep -Eq 'description\.pagination|DescriptionResource|paginate\(' "$REPO_ROOT/app/Http/Controllers/DescriptionController.php" || { logger -t ojt-ticket06 'event=failure status=red case=TC-OJT-0025 assertion=description-pagination' || :; printf '%s\n' 'FAIL [TC-OJT-0025]: description endpoint lacks paginated resource output' >&2; exit 1; }
grep -Eq 'report\.pagination|ReportResource|paginate\(' "$REPO_ROOT/app/Http/Controllers/ReportController.php" || { logger -t ojt-ticket06 'event=failure status=red case=TC-OJT-0026 assertion=report-pagination' || :; printf '%s\n' 'FAIL [TC-OJT-0026]: report endpoint lacks paginated resource output' >&2; exit 1; }
grep -Eiq 'company_id.*exists|exists.*company_id|Company::findOrFail|company.*required' "$REPO_ROOT/app/Http/Controllers/InternshipController.php" || { logger -t ojt-ticket06 'event=failure status=red case=TC-OJT-0003 assertion=company-validation' || :; printf '%s\n' 'FAIL [TC-OJT-0003]: placement company validation is not fail-closed' >&2; exit 1; }
grep -Eiq 'user_id.*Auth::id|updated_by.*Auth::id|is_approved.*0|request.*user_id|request.*updated_by' "$REPO_ROOT/app/Http/Controllers/InternshipController.php" || { logger -t ojt-ticket06 'event=failure status=red case=TC-OJT-0003 assertion=server-owned-fields' || :; printf '%s\n' 'FAIL [TC-OJT-0003]: placement server-owned fields are not explicitly protected' >&2; exit 1; }
grep -Eiq 'RequirementCategory::where.*is_deleted|foreach.*RequirementCategory|DB::transaction' "$REPO_ROOT/app/Http/Controllers/InternshipController.php" || { logger -t ojt-ticket06 'event=failure status=red case=TC-OJT-0004 assertion=requirement-transaction' || :; printf '%s\n' 'FAIL [TC-OJT-0004]: active-category requirement creation is not transactional' >&2; exit 1; }
grep -Eiq 'hours.*0\.25|fmod|quarter|date.*start_date|date.*end_date' "$REPO_ROOT/app/Http/Controllers/ReportController.php" || { logger -t ojt-ticket06 'event=failure status=red case=TC-OJT-0027 assertion=report-validation' || :; printf '%s\n' 'FAIL [TC-OJT-0027]: report quarter-hour and inclusive date validation is missing' >&2; exit 1; }
grep -Eiq 'is_deleted.*0|is_deleted.*1|paginate' "$REPO_ROOT/app/Http/Controllers/DescriptionController.php" "$REPO_ROOT/app/Http/Controllers/ReportController.php" || { logger -t ojt-ticket06 'event=failure status=red case=TC-OJT-0025 assertion=soft-delete-contract' || :; printf '%s\n' 'FAIL [TC-OJT-0025]: evidence soft-delete/list exclusion is missing' >&2; exit 1; }

# Every changed controller/policy/service method must retain the trace envelope.
cat >"$TMP_ROOT/trace_gate.php" <<'PHP'
<?php
$root=$argv[1]; chdir($root);
$files=array_filter(array_merge(explode("\n",trim(shell_exec('git diff --name-only -- app/Http/Controllers app/Policies app/Services app/Exceptions/Handler.php app/Support/PaginatedJson.php')?:'')),explode("\n",trim(shell_exec('git ls-files --others --exclude-standard -- app/Http/Controllers app/Policies app/Services app/Exceptions/Handler.php app/Support/PaginatedJson.php')?:''))));
foreach($files as $file){if(!is_file($file)||substr($file,-4)!=='.php')continue;$source=file_get_contents($file);$diff=shell_exec('git diff --unified=0 -- '.escapeshellarg($file));$ranges=[];if(trim($diff?:'')==='')$ranges[]=[1,substr_count($source,"\n")+1];foreach(preg_split('/\n/',$diff?:'') as $line)if(preg_match('/^@@ .* \+(\d+)(?:,(\d+))? @@/',$line,$m))$ranges[]=[(int)$m[1],(int)$m[1]+(isset($m[2])?(int)$m[2]:1)-1];$tokens=token_get_all($source);$line=1;$method=null;$brace=0;$body='';$start=0;foreach($tokens as $token){$text=is_array($token)?$token[1]:$token;$tl=is_array($token)?$token[2]:$line;if(is_array($token)&&$token[0]===T_FUNCTION&&$method===null){$method='';$start=$tl;$body='';}elseif($method!==null&&is_array($token)&&$method===''&&$token[0]===T_STRING)$method=$token[1];if($method!==null)$body.=$text;if($method!==null&&$text==='{')$brace++;if($method!==null&&$text==='}'){$brace--;if($brace===0&&$method!==''){$changed=false;foreach($ranges as $r)if($start<=$r[1]&&$line>=$r[0])$changed=true;if($changed&&(!strpos($body,'SessionTracer::enter')||!strpos($body,'SessionTracer::leave')||!strpos($body,'SessionTracer::exception')||!preg_match('/catch\s*\(\\?Throwable\s+\$/',$body))){fwrite(STDERR,"TRACE_GATE_FAIL $file::$method\n");exit(1);}$method=null;$body='';}}$line+=substr_count($text,"\n");}}
PHP
command -v php >/dev/null 2>&1 || { logger -t ojt-ticket06 'event=failure status=red case=TC-OJT-0011 assertion=php' || :; printf '%s\n' 'FAIL [TC-OJT-0011]: PHP is required for changed-method trace gate' >&2; exit 1; }
php "$TMP_ROOT/trace_gate.php" "$REPO_ROOT" || { logger -t ojt-ticket06 'event=failure status=red case=TC-OJT-0011 assertion=changed-method-trace' || :; printf '%s\n' 'FAIL [TC-OJT-0011]: changed placement/evidence methods lack trace enter/leave/exception' >&2; exit 1; }

[ -f "$COMPOSE_FILE" ] || { logger -t ojt-ticket06 'event=failure status=red assertion=compose-file' || :; printf '%s\n' 'FAIL [TC-OJT-0003]: compose.yaml is required' >&2; exit 1; }
command -v timeout >/dev/null 2>&1 || { logger -t ojt-ticket06 'event=failure status=red assertion=timeout' || :; printf '%s\n' 'FAIL [TC-OJT-0003]: timeout is required' >&2; exit 1; }
command -v curl >/dev/null 2>&1 || { logger -t ojt-ticket06 'event=failure status=red assertion=curl' || :; printf '%s\n' 'FAIL [TC-OJT-0003]: curl is required' >&2; exit 1; }
if command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 "$APP_PORT" >/dev/null 2>&1; then printf '%s\n' 'FAIL [TC-OJT-0003]: selected app port is already in use' >&2; exit 1; fi

# Container-only Passport probe. It stores only scalar IDs and keeps bearer
# material in memory; no token is printed, logged, or written to a file.
cat >"$TMP_ROOT/placement_evidence_probe.php" <<'PHP'
<?php
# test-10032026-Maurice: keep correlation evidence distinct from the probe's redaction sentinel.
$base=rtrim(getenv('OJT_PROBE_BASE_URL'),'/');$corr='ticket-six-correlation';$u=[];
$u['a']=\App\User::firstOrCreate(['sr_code'=>'T06-STUDENT-A'],['name'=>'Ticket06 Student A','email'=>'ticket06-a@example.invalid','password'=>bcrypt('ticket06-a'),'role'=>'student']);
$u['b']=\App\User::firstOrCreate(['sr_code'=>'T06-STUDENT-B'],['name'=>'Ticket06 Student B','email'=>'ticket06-b@example.invalid','password'=>bcrypt('ticket06-b'),'role'=>'student']);
$u['c']=\App\User::firstOrCreate(['sr_code'=>'T06-COORDINATOR'],['name'=>'Ticket06 Coordinator','email'=>'ticket06-c@example.invalid','password'=>bcrypt('ticket06-c'),'role'=>'coordinator']);
$u['s']=\App\User::firstOrCreate(['sr_code'=>'T06-SUPERUSER'],['name'=>'Ticket06 Superuser','email'=>'ticket06-s@example.invalid','password'=>bcrypt('ticket06-s'),'role'=>'superuser']);
$client=\Illuminate\Support\Facades\DB::table('oauth_personal_access_clients')->first();if(!$client){$id=\Illuminate\Support\Facades\DB::table('oauth_clients')->insertGetId(['user_id'=>null,'name'=>'T06 Probe','secret'=>hash('sha256','t06'),'redirect'=>'http://localhost','personal_access_client'=>1,'password_client'=>0,'revoked'=>0]);\Illuminate\Support\Facades\DB::table('oauth_personal_access_clients')->insert(['client_id'=>$id]);}
$tok=[];foreach($u as $k=>$v){$tok[$k]=(string)app(\Laravel\Passport\PersonalAccessTokenFactory::class)->make($v->id,'ticket06')->accessToken;if(substr_count($tok[$k],'.')!==2)throw new \RuntimeException('token-shape');}
$company=\App\Company::query()->where('is_deleted','0')->firstOrFail();$cat=\App\RequirementCategory::query()->where('is_deleted','0')->get();if($cat->count()<1)throw new \RuntimeException('no-active-category');
$post=function($who,$method,$path,$body,$want)use($base,$corr,$tok){$h=['Accept: application/json','X-Correlation-ID: '.$corr,'Authorization: Bearer '.$tok[$who]];if($body!==''){$h[]='Content-Type: application/json';}$x=curl_init($base.$path);curl_setopt_array($x,[CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_POSTFIELDS=>$body,CURLOPT_HTTPHEADER=>$h,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_CONNECTTIMEOUT=>2,CURLOPT_TIMEOUT=>5]);$r=curl_exec($x);$s=curl_getinfo($x,CURLINFO_HTTP_CODE);curl_close($x);if($s!==$want)throw new \RuntimeException('status');if($s>=400&&preg_match('/token|password|email|phone|address|T06-/i',$r))throw new \RuntimeException('unsafe-error');return $r;};
 $body=json_encode(['company_id'=>$company->id,'start_date'=>'2099-01-01','end_date'=>'2099-12-31','representative'=>'T06 Rep','student_position'=>'T06 Position','user_id'=>$u['b']->id,'updated_by'=>$u['s']->id,'is_approved'=>1]);$r=$post('a','POST','/api/internships',$body,201);$j=json_decode(substr($r,strpos($r,"\r\n\r\n")+4),true);$iid=(int)($j['data']['id']??$j['id']??0);if(!$iid)throw new \RuntimeException('placement-id');$i=\App\Internship::findOrFail($iid);if((int)$i->user_id!==(int)$u['a']->id||(int)$i->updated_by!==(int)$u['a']->id||(int)$i->is_approved!==0)throw new \RuntimeException('server-fields');$requirements=$i->requirements()->where('is_deleted','0')->get(['id','requirement_category_id']);if($requirements->count()!==$cat->count()||$requirements->pluck('id')->unique()->count()!==$requirements->count())throw new \RuntimeException('requirements-count');$activeCategoryIds=$cat->pluck('id')->map(function($id){return (int)$id;})->sort()->values()->all();$requirementCategoryIds=$requirements->pluck('requirement_category_id')->map(function($id){return (int)$id;})->sort()->values()->all();if($activeCategoryIds!==$requirementCategoryIds)throw new \RuntimeException('requirements-one-per-active-category');if($requirements->groupBy('requirement_category_id')->contains(function($rows){return $rows->count()!==1;}))throw new \RuntimeException('requirements-duplicate-category');
$post('a','POST','/api/internships',json_encode(['company_id'=>999999]),422);$post('a','POST','/api/internships',json_encode(['company_id'=>'bad']),422);$post('a','POST','/api/internships',json_encode(['company_id'=>999999,'start_date'=>'2099-01-01']),404);
 $beforeInternshipIds=\App\Internship::orderBy('id')->pluck('id')->map(function($id){return (int)$id;})->all();$beforeRequirementIds=\App\Requirement::orderBy('id')->pluck('id')->map(function($id){return (int)$id;})->all();$beforeRequirementCount=count($beforeRequirementIds);\Illuminate\Support\Facades\DB::statement("DROP TRIGGER IF EXISTS ticket06_requirement_failure");\Illuminate\Support\Facades\DB::unprepared("CREATE TRIGGER ticket06_requirement_failure BEFORE INSERT ON requirements FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ticket06 test failure'");$r=$post('a','POST','/api/internships',$body,500);$afterInternshipIds=\App\Internship::orderBy('id')->pluck('id')->map(function($id){return (int)$id;})->all();$afterRequirementIds=\App\Requirement::orderBy('id')->pluck('id')->map(function($id){return (int)$id;})->all();if($afterInternshipIds!==$beforeInternshipIds)throw new \RuntimeException('atomic-internship-leak');if(count($afterRequirementIds)!==$beforeRequirementCount||$afterRequirementIds!==$beforeRequirementIds)throw new \RuntimeException('atomic-requirement-leak');\Illuminate\Support\Facades\DB::statement("DROP TRIGGER IF EXISTS ticket06_requirement_failure");
$d=$post('a','POST','/api/descriptions',json_encode(['internship_id'=>$iid,'description'=>'T06 description']),201);$did=(int)((json_decode(substr($d,strpos($d,"\r\n\r\n")+4),true)['data']['id']??0));$post('a','GET','/api/descriptions/'.$did,'',200);$post('a','GET','/api/descriptions?page=1','',200);$post('a','GET','/api/descriptions/search/T06/internship/'.$iid.'?page=1','',200);$post('a','POST','/api/descriptions/'.$did,json_encode(['description'=>'T06 changed']),200);$post('a','DELETE','/api/descriptions/'.$did,'',204);$post('a','GET','/api/descriptions?page=1','',200);$post('b','POST','/api/descriptions',json_encode(['internship_id'=>$iid,'description'=>'cross']),403);
 $reportIds=[];foreach(['0.25','24','8.25'] as $h){$r=$post('a','POST','/api/reports',json_encode(['internship_id'=>$iid,'description'=>'T06 report '.$h,'date'=>'2099-01-01','hours'=>$h]),201);$j=json_decode(substr($r,strpos($r,"\r\n\r\n")+4),true);$reportIds[]=(int)($j['data']['id']??$j['id']??0);}foreach(['0','24.25','8.1'] as $h)$post('a','POST','/api/reports',json_encode(['internship_id'=>$iid,'description'=>'bad','date'=>'2099-01-01','hours'=>$h]),422);$post('a','POST','/api/reports',json_encode(['internship_id'=>$iid,'description'=>'bad','date'=>'2098-12-31','hours'=>'8']),422);$post('a','GET','/api/reports?page=1','',200);$post('a','GET','/api/reports/internship/'.$iid.'?page=1','',200);$post('a','GET','/api/reports/search/T06/internship/'.$iid.'?page=1','',200);$post('a','GET','/api/reports/'.$reportIds[0],'',200);$post('a','POST','/api/reports/'.$reportIds[0],json_encode(['description'=>'T06 report updated','date'=>'2099-12-31','hours'=>'8.25']),200);$post('b','POST','/api/reports/'.$reportIds[0],json_encode(['description'=>'cross','date'=>'2099-01-01','hours'=>'8']),403);$post('a','DELETE','/api/reports/'.$reportIds[2],'',204);$post('a','POST','/api/reports/'.$reportIds[1],json_encode(['is_valid'=>1]),403);$post('c','POST','/api/reports/'.$reportIds[0],json_encode(['is_valid'=>1]),200);$post('s','POST','/api/reports/'.$reportIds[1],json_encode(['is_valid'=>1]),200);$reviewedHttp0=$post('s','GET','/api/reports/'.$reportIds[0],'',200);$reviewedHttp1=$post('c','GET','/api/reports/'.$reportIds[1],'',200);foreach([[$reportIds[0],$reviewedHttp0],[$reportIds[1],$reviewedHttp1]] as $reviewedPair){$reviewedId=$reviewedPair[0];$reviewedPayload=json_decode(substr($reviewedPair[1],strpos($reviewedPair[1],"\r\n\r\n")+4),true);if((int)($reviewedPayload['data']['is_valid']??$reviewedPayload['is_valid']??-1)!==1)throw new \RuntimeException('review-fetch-is-valid');$reviewed=\App\Report::findOrFail($reviewedId);if((int)$reviewed->is_valid!==1)throw new \RuntimeException('review-persisted-is-valid');}
 $preDeleteRequirementIds=\App\Requirement::where('internship_id',$iid)->orderBy('id')->pluck('id')->map(function($id){return (int)$id;})->all();$preDeleteRequirementCount=count($preDeleteRequirementIds);$post('a','POST','/api/internships/'.$iid,json_encode(['start_date'=>'2099-02-01','user_id'=>$u['b']->id,'is_approved'=>1]),200);$post('a','DELETE','/api/internships/'.$iid,'',204);$post('a','GET','/api/internships/'.$iid,'',404);$post('a','GET','/api/requirements/internship/'.$iid,'',404);$post('a','GET','/api/requirements/search/T06/internship/'.$iid,'',404);$postDeleteRequirementIds=\App\Requirement::where('internship_id',$iid)->orderBy('id')->pluck('id')->map(function($id){return (int)$id;})->all();if(count($postDeleteRequirementIds)!==$preDeleteRequirementCount||$postDeleteRequirementIds!==$preDeleteRequirementIds)throw new \RuntimeException('deleted-placement-requirement-lazy-generation');
PHP

export COMPOSE_PROJECT_NAME=$PROJECT_NAME APP_PORT OJT_PROBE_BASE_URL=${OJT_PROBE_BASE_URL:-http://nginx:8080} ACADEMIC_PROVIDER_MODE=fake OJT_TEST_NO_PROVIDER_CALLS=1 AGENT_SESSION_ID
logger -t ojt-ticket06 'event=major-operation status=compose-up cases=TC-OJT-0003,TC-OJT-0004,TC-OJT-0007,TC-OJT-0010,TC-OJT-0011,TC-OJT-0025,TC-OJT-0026,TC-OJT-0027' || :
timeout "${OJT_TEST_BUILD_TIMEOUT_SECONDS:-180}" docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" up -d --build >"$TMP_ROOT/compose.log" 2>&1
COMPOSE_STARTED=1
TRIGGER_INSTALLED=1
chmod 0644 "$TMP_ROOT/placement_evidence_probe.php"
timeout 20 docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" cp "$TMP_ROOT/placement_evidence_probe.php" php-fpm:/tmp/placement_evidence_probe.php >"$TMP_ROOT/probe-copy.log" 2>&1
# test-10032026-Maurice: pass the probe endpoint into php-fpm; never bypass the HTTP contract.
timeout 30 docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" exec -T -e OJT_PROBE_BASE_URL="$OJT_PROBE_BASE_URL" php-fpm sh -c 'export APP_KEY=$(cat /run/ojt-secrets/app.key); export DB_PASSWORD=$(cat /run/ojt-secrets/db.app.password); php -r '\''require "/var/www/html/vendor/autoload.php"; $app=require "/var/www/html/bootstrap/app.php"; $app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap(); require "/tmp/placement_evidence_probe.php";'\''' >"$TMP_ROOT/probe.log" 2>&1 || { logger -t ojt-ticket06 'event=failure status=red case=TC-OJT-0003 assertion=runtime-probe' || :; printf '%s\n' 'FAIL [TC-OJT-0003]: placement/evidence runtime probe failed' >&2; sed -n '1,30p' "$TMP_ROOT/probe.log" >&2; exit 1; }
if grep -Eiq 'token|password|email|phone|address|T06-|provider|academic|api[_-]?key' "$TMP_ROOT/probe.log"; then logger -t ojt-ticket06 'event=failure status=red case=TC-OJT-0011 assertion=probe-redaction' || :; printf '%s\n' 'FAIL [TC-OJT-0011]: runtime output contains secret, PII, or provider material' >&2; exit 1; fi
logger -t ojt-ticket06 'event=pass status=complete test=ticket06_placement_evidence_test' || :
printf '%s\n' 'PASS: Ticket 06 placement/evidence contract'
