<?php
namespace App\Http\Controllers;
use App\Http\Resources\RequirementCollection;
use App\Internship;
use App\Requirement;
use App\RequirementCategory;
use App\Support\SessionTracer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

/* security-10032026-Maurice: requirement verification is privileged and server-attributed. */
class RequirementController extends Controller
{
    public function index($id) { $s=microtime(true);$c=SessionTracer::id(request()->header('X-Correlation-ID'));SessionTracer::enter('requirement.index',$c,array('resource_type'=>'requirement','resource_id'=>(string)$id));try{/* catch (?Throwable $trace contract */$i=Internship::where('is_deleted','0')->findOrFail($id);abort_unless(Auth::user()->role!=='student'||(int)$i->user_id===(int)Auth::id(),403);$existing=Requirement::where('is_deleted','0')->where('internship_id',$id)->get();foreach(RequirementCategory::where('is_deleted','0')->orderBy('name','ASC')->get() as $category){if(!$existing->contains('requirement_category_id',$category->id))Requirement::create(array('requirement_category_id'=>$category->id,'internship_id'=>$id,'updated_by'=>Auth::id()));}$r=\App\Support\PaginatedJson::response(Requirement::where('is_deleted','0')->where('internship_id',$id)->whereHas('requirement_category',function($q){$q->where('is_deleted','0');})->paginate(5),\App\Http\Resources\Requirement::class,request(),'requirement.pagination.index');SessionTracer::leave('requirement.index',$c,$s,'success',array('resource_type'=>'requirement','resource_id'=>(string)$id));return $r;}catch (\Throwable $e){SessionTracer::exception('requirement.index',$c,$s,'requirement_unexpected',$e);throw $e;} }
    public function search($value,$id) { $s=microtime(true);$c=SessionTracer::id(request()->header('X-Correlation-ID'));SessionTracer::enter('requirement.search',$c,array('resource_type'=>'requirement','resource_id'=>(string)$id));try{/* catch (?Throwable $trace contract */$i=Internship::where('is_deleted','0')->findOrFail($id);abort_unless(Auth::user()->role!=='student'||(int)$i->user_id===(int)Auth::id(),403);$r=\App\Support\PaginatedJson::response(Requirement::where('is_deleted','0')->where('internship_id',$id)->whereHas('requirement_category',function($q)use($value){$q->where('name','LIKE','%'.$value.'%')->where('is_deleted','0');})->paginate(5),\App\Http\Resources\Requirement::class,request(),'requirement.pagination.search');SessionTracer::leave('requirement.search',$c,$s,'success',array('resource_type'=>'requirement','resource_id'=>(string)$id));return $r;}catch (\Throwable $e){SessionTracer::exception('requirement.search',$c,$s,'requirement_unexpected',$e);throw $e;} }
    /* fix-10032026-Maurice: approval accepts only Laravel boolean values, never arbitrary strings. */
    public function update(Request $request,$id) { $s=microtime(true);$c=SessionTracer::id($request->header('X-Correlation-ID'));SessionTracer::enter('requirement.update',$c,array('resource_type'=>'requirement','resource_id'=>(string)$id));try{/* feature/fix-10042026-Maurice: approved requirements remain immutable until reopen; catch (?Throwable $trace contract */abort_unless(in_array(Auth::user()->role,array('coordinator','superuser'),true),403);$r=Requirement::findOrFail($id);abort_unless((int)$r->is_deleted===0,404);$i=Internship::where('is_deleted','0')->findOrFail($r->internship_id);abort_unless((int)$i->is_approved===0,403);$request->validate(array('is_approved'=>'required|boolean'));/* fix-10032026-Maurice: normalize only after strict boolean validation for legacy Laravel compatibility. */$r->is_approved=filter_var($request->input('is_approved'),FILTER_VALIDATE_BOOLEAN)?'1':'0';$r->updated_by=Auth::id();$r->save();SessionTracer::leave('requirement.update',$c,$s,'success',array('resource_type'=>'requirement','resource_id'=>(string)$id));return response()->json(array('message'=>'Requirement updated successfully!'),200);}catch (\Throwable $e){SessionTracer::exception('requirement.update',$c,$s,'requirement_unexpected',$e);throw $e;} }
}
